### PR TITLE
add userSearchBase and groupSearchBase to security/RBAC config  [skip secret scan]

### PR DESCRIPTION
**Pull request by ptyagii**
https://github.com/confluentinc/confluent-kubernetes-examples/issues/82

### CODE REVIEW

**Comment by MosheBlumbergX** [comment]
Hi @ptyagii , thank you for adding these. 

I don't think we should be adding default configs to properties / YAML file.
You wouldn't do it with other deployments. 

The addition makes the YAML file looks over bloated. 
If a user wants to investigate what properties can be used he can check the API reference
https://docs.confluent.io/operator/current/co-api.html#tag/Kafka

**Comment by ptyagii** [comment]
hey @rohit2b @yangpei1214 can you please review this PR?

**Comment by yangpei1214** [comment]
lgtm, thanks @ptyagii. By default user/group searchGroup is set to 1. even with those should also be fine. Is this requested from customer?

**Review by MosheBlumbergX — APPROVED** [review]

**Comment by MosheBlumbergX** [comment]
LGTM

**Comment by MosheBlumbergX** [comment]
@ptyagii , I've enabled the auto commit , but you need to resolve the conflicts before as I can't do it.

**Pull request merged**
