### PR TITLE
Revert "Clarifications to bring the CP component clusters using LB"

### PR DESCRIPTION
**Pull request by arodoni**
This reverts commit a207eeb25db5dd12304be485d1b16eab77a5dd8a.

### CODE REVIEW

**Review by bleporini — APPROVED** [review]
I'm ok but why removing the documentation? We can have dummy domain values and the documentation, can't we?

**Comment by MosheBlumbergX** [comment]
@arodoni , thank you for putting this PR together. 
I think we should leave the readme file as is and not remove the DNS portion of things as it's a good example of what is needed. 

The only change that I think is needed is to the yaml file adding a default value.

**Review by MosheBlumbergX — CHANGES_REQUESTED** [review]
lets leave the README portion as is please

**Comment by arodoni** [comment]
> lets leave the README portion as is please

Did put back the README file per request.

**Pull request merged**
