### PR TITLE
Adding a new TLS secret for ZK.

### PR DESCRIPTION
**Pull request by bleporini**

### CODE REVIEW

**Comment by MosheBlumbergX** [comment]
@bleporini , thank you for submitting the PR, what's the reason for it? is it just to split the broker and zookeeper certs? 
I think you would also need to change the appendix cert name if you renaming all of the certs.

**Comment by rohit2b** [comment]
Hi @bleporini - in this scenario we walk through how to have separate certs per component: https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/userprovided-tls_mtls_confluent-rbac

That scenario uses these scripts to create server certificates per component: https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/assets/certs/component-certs

With this other scenario in place, is there a benefit to this Zookeeper separation here?

**Comment by bleporini** [comment]
Sorry I forgot the description. In fact the way certificates are generated has changed: initially ZK and Kafka used the same certificate `server.pem`, but at some point it became `kafka-server.pem` and `zookeeper-server.pem` and there was no `server.pem`  generated. So the procedure detailed in https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/production-secure-deploy failed and replacing `server-key.pem` with `kafka-server-key.pem` makes ZK cluster failing because of hostname verification during TLS handshake:
```
[ERROR] 2021-08-23 14:31:24,008 [QuorumConnectionThread-[myid=0]-1] org.apache.zookeeper.common.ZKTrustManager performHostVerification - Failed to verify hostname: zookeeper-1.zookeeper.confluent.svc.cluster.local
 970   │ javax.net.ssl.SSLPeerUnverifiedException: Certificate for <zookeeper-1.zookeeper.confluent.svc.cluster.local> doesn't match any of the subject alternative names: [kafka, *.my.domain, kafka.confluent.svc.cluster.local, *.kafka.confluent.svc.cluster.local]
```
The only purpose for this PR is to fix `production-secure-deploy/ confluent-platform-production.yaml`.

**Comment by MosheBlumbergX** [comment]
@bleporini you're still however missing zookeeper-server.pem , this is never generated

**Pull request closed without merging**
