### PR TITLE
ClusterLink playbook/examples[skip secret scan]

### PR DESCRIPTION
**Pull request by karthikeyanas**
Similar to https://github.com/confluentinc/confluent-operator/tree/master/playbooks/features/clusterlink

### CODE REVIEW

**Comment by rohit2b** [comment]
@karthikeyanas in general this looks good! Two review comments to incorporate:
1. Let's move the parent folder for these scenarios to https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/hybrid/...
2. In the component CustomResources, we don't need `pullSecretRef: - confluent-registry` as the containers are being pulled from publicly accessible Dockerhub - `confluentinc/cp-server:7.0.0`

**Review by rohit2b — CHANGES_REQUESTED** [review]
@karthikeyanas in general this looks good! Two review comments to incorporate:
1. Let's move the parent folder for these scenarios to https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/hybrid/...
2. In the component CustomResources, we don't need `pullSecretRef: - confluent-registry` as the containers are being pulled from publicly accessible Dockerhub - `confluentinc/cp-server:7.0.0`

**Comment by karthikeyanas** [comment]
> @karthikeyanas in general this looks good! Two review comments to incorporate:
> 
> 1. Let's move the parent folder for these scenarios to https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/hybrid/...
> 2. In the component CustomResources, we don't need `pullSecretRef: - confluent-registry` as the containers are being pulled from publicly accessible Dockerhub - `confluentinc/cp-server:7.0.0`

Thanks @rohit2b . I have addressed these comments.

**Review by rohit2b — APPROVED** [review]
LGTM!

**Pull request merged**
